[package]
name = "franz"
version = "0.1.0"
authors = ["teivah <t.harsanyi@thebeat.co>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
